<?php defined( 'ABSPATH' ) || exit; $items = fp_items( 'package' ); $tier_images = array( 'proposal', 'hero', 'villa' ); ?>
<section id="packages" class="section panel"><div class="container">
<?php fp_title( 'Curated displays', 'Fireworks packages', 'Broad price guides for Phuket celebrations. Every display is refined around your venue, timing and desired atmosphere.' ); ?>
<div class="grid three package-grid">
<?php if ( $items ) : foreach ( $items as $i => $item ) : ?>
<?php $price = absint( get_post_meta( $item->ID, '_fp_start_price', true ) ); ?>
<article class="package-card"><div class="package-image"><?php if ( has_post_thumbnail( $item ) ) { echo get_the_post_thumbnail( $item, 'large', array( 'loading' => 'lazy' ) ); } else { fp_image( $tier_images[ $i % 3 ], $item->post_title . ' fireworks inspiration' ); } ?></div><div class="card-body"><div class="card-meta"><p class="eyebrow"><?php echo esc_html( get_the_excerpt( $item ) ); ?></p><span><?php echo esc_html( sprintf( '%02d', $i + 1 ) ); ?></span></div><h3><?php echo esc_html( $item->post_title ); ?></h3><div class="copy"><?php fp_item_content( $item ); ?></div><p class="price"><?php echo $price ? 'Around ฿' . esc_html( number_format_i18n( $price ) ) . '+' : 'Request pricing'; ?></p><a class="card-link" href="<?php echo esc_url( fp_contact_url() ); ?>">Request this package <span>→</span></a></div></article>
<?php endforeach; else : foreach ( array( array( 'Classic', 'Intimate moments', 'Ideal for intimate weddings, proposals and smaller celebrations.', 40000 ), array( 'Signature', 'A balanced finale', 'A fuller display with stronger pacing and a memorable finale.', 70000 ), array( 'Grand', 'Maximum impact', 'A large-scale display designed for major weddings, resorts and events.', 108000 ) ) as $i => $package ) : ?>
<article class="package-card"><div class="package-image"><?php fp_image( $tier_images[ $i ], $package[0] . ' fireworks inspiration' ); ?></div><div class="card-body"><div class="card-meta"><p class="eyebrow"><?php echo esc_html( $package[1] ); ?></p><span>0<?php echo esc_html( $i + 1 ); ?></span></div><h3><?php echo esc_html( $package[0] ); ?></h3><p class="copy"><?php echo esc_html( $package[2] ); ?></p><p class="price">Around ฿<?php echo esc_html( number_format_i18n( $package[3] ) ); ?>+</p><a class="card-link" href="<?php echo esc_url( fp_contact_url() ); ?>">Request this package <span>→</span></a></div></article>
<?php endforeach; endif; ?></div><p class="small copy">Approximate guide prices in THB. VAT, permission fees, venue charges and special logistics are additional. Final pricing, inclusions and timing are confirmed in a written quote.</p></div></section>
