<?php defined( 'ABSPATH' ) || exit;
$proposal_options = array(
    array( __( 'The Intimate Reveal', 'fireworks-phuket' ), 'concept-fire-letters.webp', __( 'Concept of MARRY ME spelled in fire letters on a beach at dusk', 'fireworks-phuket' ), __( 'A personal proposal centred on a “Marry Me” reveal. Ask about fire letters, an illuminated alternative and a discreetly coordinated cue.', 'fireworks-phuket' ), __( 'Tailored quote', 'fireworks-phuket' ), __( 'Letters, location and setup quoted to suit your plans.', 'fireworks-phuket' ), 'the-intimate-reveal' ),
    array( __( 'The Sparkling Yes', 'fireworks-phuket' ), 'concept-marry-me.webp', __( 'Concept of a romantic proposal with illuminated letters and sparklers', 'fireworks-phuket' ), __( 'Pair your proposal reveal with a private fireworks moment. Sparklers, letters, flowers or photography can be discussed as separate additions.', 'fireworks-phuket' ), __( 'Fireworks guide: ฿40,000+', 'fireworks-phuket' ), __( 'Proposal setup and all extras quoted separately.', 'fireworks-phuket' ), 'the-sparkling-yes' ),
    array( __( 'The Grand Proposal', 'fireworks-phuket' ), 'proposal-fireworks.jpg', __( 'Fireworks inspiration for a larger proposal finale', 'fireworks-phuket' ), __( 'Build a fuller celebration around your big question, with a larger fireworks finale and optional live fire performance.', 'fireworks-phuket' ), __( 'Fireworks guide: ฿70,000+', 'fireworks-phuket' ), __( 'Fire performance, proposal setup and extras quoted separately.', 'fireworks-phuket' ), 'the-grand-proposal' ),
);
?>
<section id="proposals" class="section proposals bordered"><div class="container">
<?php fp_title( __( 'Make the question unforgettable', 'fireworks-phuket' ), __( 'Proposal packages in Phuket', 'fireworks-phuket' ), __( 'Three starting points for your “Marry Me” moment. Choose the feeling you want, then we will shape a written proposal around your venue, date and budget.', 'fireworks-phuket' ) ); ?>
<div class="proposal-grid">
<?php foreach ( $proposal_options as $option ) : ?>
<article class="proposal-card"><?php if ( $option[1] ) : ?><img src="<?php echo esc_url( get_template_directory_uri() . '/assets/images/' . $option[1] ); ?>" alt="<?php echo esc_attr( $option[2] ); ?>" width="1600" height="900" loading="lazy" decoding="async"><?php endif; ?><div class="proposal-card-copy"><h3><?php echo esc_html( $option[0] ); ?></h3><p class="copy"><?php echo esc_html( $option[3] ); ?></p><?php if ( ! is_front_page() ) : ?><p class="proposal-price"><?php echo esc_html( $option[4] ); ?></p><?php endif; ?><p class="small copy"><?php echo esc_html( $option[5] ); ?></p><a class="text-link" href="<?php echo esc_url( add_query_arg( 'proposal', $option[6], fp_page_url( 'contact', 'contact' ) ) . '#quote-form' ); ?>"><?php esc_html_e( 'Plan this proposal →', 'fireworks-phuket' ); ?></a></div></article>
<?php endforeach; ?>
</div><p class="small copy concept-disclosure"><?php esc_html_e( 'Images show concept and display inspiration, not guaranteed package inclusions. Fire-letter and sparkler options depend on venue approval and supplier availability. The fireworks guides exclude 7% VAT, permission fees, venue charges and special logistics; a full proposal total is confirmed in writing.', 'fireworks-phuket' ); ?></p>
<?php if ( ! fp_is_page( 'proposals' ) ) : ?><p class="proposal-more"><a class="text-link" href="<?php echo esc_url( fp_page_url( 'proposals', 'proposals' ) ); ?>"><?php esc_html_e( 'Explore proposal packages →', 'fireworks-phuket' ); ?></a></p><?php endif; ?>
</div></section>
