<?php defined( 'ABSPATH' ) || exit; $items = fp_items( 'package' ); ?>
<section id="packages" class="section panel"><div class="container">
<?php fp_title( 'Curated displays', 'Fireworks packages', 'A starting point for your celebration. Every show is refined around your venue, timing and desired atmosphere.' ); ?>
<div class="grid three package-grid">
<?php if ( $items ) : foreach ( $items as $item ) : ?>
<article class="package-card"><div class="package-image"><?php if ( has_post_thumbnail( $item ) ) { echo get_the_post_thumbnail( $item, 'large', array( 'loading' => 'lazy' ) ); } else { fp_image( 'hero', 'Fireworks display in Phuket' ); } ?></div><div class="card-body"><h3><?php echo esc_html( $item->post_title ); ?></h3><div class="copy"><?php fp_item_content( $item ); ?></div><a class="card-link" href="<?php echo esc_url( fp_contact_url() ); ?>">Request this package <span>→</span></a></div></article>
<?php endforeach; else : foreach ( array( array( 'Classic', 'Intimate moments', 'Ideal for intimate weddings, proposals and smaller celebrations.' ), array( 'Signature', 'Most requested', 'A fuller display with stronger pacing and a memorable finale.' ), array( 'Grand', 'Maximum impact', 'A large-scale display designed for major weddings, resorts and events.' ) ) as $i => $package ) : ?>
<article class="package-card"><div class="package-image"><?php fp_image( 'hero', 'Fireworks display inspiration' ); ?></div><div class="card-body"><div class="card-meta"><p class="eyebrow"><?php echo esc_html( $package[1] ); ?></p><span>0<?php echo esc_html( $i + 1 ); ?></span></div><h3><?php echo esc_html( $package[0] ); ?></h3><p class="copy"><?php echo esc_html( $package[2] ); ?></p><p class="price">Request pricing</p><a class="card-link" href="<?php echo esc_url( fp_contact_url() ); ?>">Request this package <span>→</span></a></div></article>
<?php endforeach; endif; ?></div><p class="small copy">Final pricing depends on venue, location, duration, show design, access and permissions.</p></div></section>
