<?php defined( 'ABSPATH' ) || exit; $items = fp_items( 'package' ); $tier_images = array( 'proposal', 'wedding', 'villa' ); ?>
<section id="packages" class="section panel"><div class="container">
<?php fp_title( __( 'Curated displays', 'fireworks-phuket' ), __( 'Fireworks packages', 'fireworks-phuket' ), __( 'Explore display options for Phuket celebrations. Every display is refined around your venue, timing and desired atmosphere.', 'fireworks-phuket' ) ); ?>
<div class="grid three package-grid">
<?php if ( $items ) : foreach ( $items as $i => $item ) : ?>
<?php $price = absint( get_post_meta( $item->ID, '_fp_start_price', true ) ); ?>
<article class="package-card"><div class="package-image"><?php if ( has_post_thumbnail( $item ) ) { echo get_the_post_thumbnail( $item, 'large', array( 'loading' => 'lazy' ) ); } else { fp_image( $tier_images[ $i % 3 ], sprintf( __( '%s fireworks inspiration', 'fireworks-phuket' ), $item->post_title ) ); } ?></div><div class="card-body"><div class="card-meta"><p class="eyebrow"><?php echo esc_html( get_the_excerpt( $item ) ); ?></p><span><?php echo esc_html( sprintf( '%02d', $i + 1 ) ); ?></span></div><h3><?php echo esc_html( $item->post_title ); ?></h3><div class="copy"><?php fp_item_content( $item ); ?></div><?php if ( ! is_front_page() ) : ?><p class="price"><?php echo esc_html( $price ? sprintf( __( 'Around ฿%s+', 'fireworks-phuket' ), number_format_i18n( $price ) ) : __( 'Request pricing', 'fireworks-phuket' ) ); ?></p><?php endif; ?><a class="card-link" href="<?php echo esc_url( add_query_arg( 'package', $item->post_name, fp_page_url( 'contact' ) ) . '#quote-form' ); ?>"><?php esc_html_e( 'Request this package', 'fireworks-phuket' ); ?> <span>→</span></a></div></article>
<?php endforeach; else : foreach ( array( array( 'Classic', __( 'Intimate moments', 'fireworks-phuket' ), __( 'Ideal for intimate weddings, proposals and smaller celebrations.', 'fireworks-phuket' ), 40000 ), array( 'Signature', __( 'A balanced finale', 'fireworks-phuket' ), __( 'A fuller display with stronger pacing and a memorable finale.', 'fireworks-phuket' ), 70000 ), array( 'Grand', __( 'Maximum impact', 'fireworks-phuket' ), __( 'A large-scale display designed for major weddings, resorts and events.', 'fireworks-phuket' ), 108000 ) ) as $i => $package ) : ?>
<article class="package-card"><div class="package-image"><?php fp_image( $tier_images[ $i ], sprintf( __( '%s fireworks inspiration', 'fireworks-phuket' ), $package[0] ) ); ?></div><div class="card-body"><div class="card-meta"><p class="eyebrow"><?php echo esc_html( $package[1] ); ?></p><span>0<?php echo esc_html( $i + 1 ); ?></span></div><h3><?php echo esc_html( $package[0] ); ?></h3><p class="copy"><?php echo esc_html( $package[2] ); ?></p><?php if ( ! is_front_page() ) : ?><p class="price"><?php echo esc_html( sprintf( __( 'Around ฿%s+', 'fireworks-phuket' ), number_format_i18n( $package[3] ) ) ); ?></p><?php endif; ?><a class="card-link" href="<?php echo esc_url( add_query_arg( 'package', sanitize_title( $package[0] ), fp_page_url( 'contact' ) ) . '#quote-form' ); ?>"><?php esc_html_e( 'Request this package', 'fireworks-phuket' ); ?> <span>→</span></a></div></article>
<?php endforeach; endif; ?></div><?php if ( is_front_page() ) : ?><p><a class="text-link" href="<?php echo esc_url( fp_page_url( 'packages' ) ); ?>"><?php esc_html_e( 'View package details and starting prices →', 'fireworks-phuket' ); ?></a></p><?php else : ?><p class="small copy"><?php esc_html_e( 'Approximate guide prices in THB. VAT, permission fees, venue charges and special logistics are additional. Final pricing, inclusions and timing are confirmed in a written quote.', 'fireworks-phuket' ); ?></p><?php endif; ?></div></section>
