<?php defined( 'ABSPATH' ) || exit; $proposal_key = isset( $_GET['proposal'] ) && is_string( $_GET['proposal'] ) ? sanitize_key( wp_unslash( $_GET['proposal'] ) ) : ''; $proposal_labels = array( 'the-intimate-reveal' => __( 'The Intimate Reveal', 'fireworks-phuket' ), 'the-sparkling-yes' => __( 'The Sparkling Yes', 'fireworks-phuket' ), 'the-grand-proposal' => __( 'The Grand Proposal', 'fireworks-phuket' ) ); $proposal = $proposal_labels[$proposal_key] ?? ''; $fire_key = isset( $_GET['fire_show'] ) && is_string( $_GET['fire_show'] ) ? sanitize_key( wp_unslash( $_GET['fire_show'] ) ) : ''; $fire_labels = array( '2' => __( 'Duo Rhythm — 2 dancers', 'fireworks-phuket' ), '3' => __( 'Choreographed Trio — 3 dancers', 'fireworks-phuket' ), '4' => __( 'Ensemble — 4 dancers', 'fireworks-phuket' ), '5' => __( 'Signature Troupe — 5 dancers', 'fireworks-phuket' ) ); $fire_show = $proposal ? '' : ( $fire_labels[$fire_key] ?? '' );  $status = isset( $_GET['inquiry'] ) && is_string( $_GET['inquiry'] ) ? sanitize_key( wp_unslash( $_GET['inquiry'] ) ) : ''; ?>
<?php
$package_key = isset( $_GET['package'] ) && is_string( $_GET['package'] ) ? sanitize_title( wp_unslash( $_GET['package'] ) ) : '';
$package_label = '';
if ( ! $proposal && ! $fire_show && $package_key ) {
    $package_items = fp_items( 'package' );
    foreach ( $package_items as $package_item ) {
        if ( $package_item->post_name === $package_key ) { $package_label = $package_item->post_title; break; }
    }
    if ( ! $package_items ) { $package_label = array( 'classic' => 'Classic', 'signature' => 'Signature', 'grand' => 'Grand' )[$package_key] ?? ''; }
}
?>
<section class="section"><div class="container quote-grid" id="quote-form"><div><p class="eyebrow"><?php esc_html_e( 'Request a quote', 'fireworks-phuket' ); ?></p><h2><?php esc_html_e( 'Tell us about your celebration.', 'fireworks-phuket' ); ?></h2><p class="copy"><?php esc_html_e( 'Share what you know so far. We’ll recommend a fireworks display, proposal package, fire dance show or a combination based on your date, venue and plans.', 'fireworks-phuket' ); ?></p><p><?php esc_html_e( 'Phuket · Khao Lak · Krabi', 'fireworks-phuket' ); ?></p><?php fp_intake_note(); ?></div><div>
<?php $messages = array( 'saved' => __( 'Thank you — your inquiry is saved. Our team will review your plans and contact you using the details you provided.', 'fireworks-phuket' ), 'expired' => __( 'This form expired. Please enter your details and submit again.', 'fireworks-phuket' ), 'invalid' => __( 'Please check your details, enter a valid upcoming date, and provide a phone number, email or messaging app ID.', 'fireworks-phuket' ), 'wait' => __( 'Please wait a minute before sending another inquiry.', 'fireworks-phuket' ), 'error' => __( 'We could not save your inquiry. Please try again.', 'fireworks-phuket' ) ); ?>
<?php if ( isset( $messages[$status] ) ) : ?><p class="form-notice" role="status"><?php echo esc_html( $messages[$status] ); ?></p><?php endif; ?>
<?php if ( 'saved' !== $status ) : ?><form class="quote-form" method="post" action="<?php echo esc_url( admin_url( 'admin-post.php' ) ); ?>">
<input type="hidden" name="action" value="fp_inquiry"><input type="hidden" name="lang" value="<?php echo esc_attr( fp_lang() ); ?>"><?php wp_nonce_field( 'fp_inquiry', 'fp_nonce' ); ?>
<div class="honeypot" aria-hidden="true"><label><?php esc_html_e( 'Leave this empty', 'fireworks-phuket' ); ?><input name="website" type="text" tabindex="-1" autocomplete="off"></label></div>
<label><?php esc_html_e( 'Name', 'fireworks-phuket' ); ?> <span aria-hidden="true">*</span><input name="name" required autocomplete="name" maxlength="300"></label>
<label><?php esc_html_e( 'Phone (optional)', 'fireworks-phuket' ); ?><input name="phone" type="tel" autocomplete="tel" maxlength="300"></label>
<label><?php esc_html_e( 'Email', 'fireworks-phuket' ); ?><input name="email" type="email" autocomplete="email" maxlength="300"></label>
<label><?php esc_html_e( 'Preferred way to reach you', 'fireworks-phuket' ); ?><select name="preferred"><option value="Email"><?php esc_html_e( 'Email', 'fireworks-phuket' ); ?></option><?php foreach ( fp_contact_apps() as $app ) : ?><option value="<?php echo esc_attr( $app ); ?>"><?php echo esc_html( $app ); ?></option><?php endforeach; ?><option value="Phone call"><?php esc_html_e( 'Phone call', 'fireworks-phuket' ); ?></option></select></label>
<label><?php esc_html_e( 'Your app username or ID', 'fireworks-phuket' ); ?><input name="handle" maxlength="300" autocomplete="off"></label>
<label><?php esc_html_e( 'Event date', 'fireworks-phuket' ); ?> <span aria-hidden="true">*</span><input name="date" type="date" required min="<?php echo esc_attr( wp_date( 'Y-m-d' ) ); ?>"></label>
<label><?php esc_html_e( 'Venue / location', 'fireworks-phuket' ); ?> <span aria-hidden="true">*</span><input name="venue" required maxlength="300"></label>
<label><?php esc_html_e( 'Interested in', 'fireworks-phuket' ); ?><select name="service"><option value=""><?php esc_html_e( 'Please select', 'fireworks-phuket' ); ?></option><option value="Proposal package" <?php selected( (bool) $proposal ); ?>><?php esc_html_e( 'Proposal package', 'fireworks-phuket' ); ?></option><option value="Fireworks" <?php selected( (bool) $package_label ); ?>><?php esc_html_e( 'Fireworks', 'fireworks-phuket' ); ?></option><option value="Fire dance show" <?php selected( (bool) $fire_show ); ?>><?php esc_html_e( 'Fire dance show', 'fireworks-phuket' ); ?></option><option value="Fireworks and fire dance show"><?php esc_html_e( 'Both fireworks and fire dance', 'fireworks-phuket' ); ?></option></select></label>
<label><?php esc_html_e( 'Event type', 'fireworks-phuket' ); ?><input name="event" maxlength="300" value="<?php echo $proposal ? esc_attr( sprintf( __( 'Marriage proposal — %s', 'fireworks-phuket' ), $proposal ) ) : ''; ?>"></label>
<label><?php esc_html_e( 'Approximate budget (THB)', 'fireworks-phuket' ); ?><select name="budget"><option value=""><?php esc_html_e( 'Please select', 'fireworks-phuket' ); ?></option><?php foreach ( array( 'Less than 35,000' => __( 'Less than 35,000', 'fireworks-phuket' ), '35,000 – 65,000' => '35,000 – 65,000', '65,000 – 95,000' => '65,000 – 95,000', '95,000 – 125,000' => '95,000 – 125,000', 'More than 125,000' => __( 'More than 125,000', 'fireworks-phuket' ) ) as $range => $range_label ) : ?><option value="<?php echo esc_attr( $range ); ?>"><?php echo esc_html( $range_label ); ?></option><?php endforeach; ?></select></label>
<label><?php esc_html_e( 'Preferred show duration', 'fireworks-phuket' ); ?><select name="duration"><option value=""><?php esc_html_e( 'Please select', 'fireworks-phuket' ); ?></option><?php foreach ( array( '30 seconds' => __( '30 seconds', 'fireworks-phuket' ), '1 minute' => __( '1 minute', 'fireworks-phuket' ), '2 minutes' => __( '2 minutes', 'fireworks-phuket' ), '3 minutes' => __( '3 minutes', 'fireworks-phuket' ), '4 minutes' => __( '4 minutes', 'fireworks-phuket' ), '5+ minutes' => __( '5+ minutes', 'fireworks-phuket' ), 'Fire Dance (15 min+)' => __( 'Fire Dance (15 min+)', 'fireworks-phuket' ), 'Other' => __( 'Other', 'fireworks-phuket' ) ) as $length => $length_label ) : ?><option value="<?php echo esc_attr( $length ); ?>"><?php echo esc_html( $length_label ); ?></option><?php endforeach; ?></select></label>
<label id="duration-other-wrap"><?php esc_html_e( 'Please specify the duration', 'fireworks-phuket' ); ?><input name="duration_other" maxlength="300"></label>
<label class="full"><?php esc_html_e( 'Tell us what you have in mind', 'fireworks-phuket' ); ?><textarea name="message" rows="5" maxlength="4000"></textarea></label>
<p class="small copy full"><?php esc_html_e( 'Please provide at least one contact method: phone, email or a messaging app ID. We’ll use your details to respond to your inquiry.', 'fireworks-phuket' ); ?></p>
<button class="button full" type="submit"><?php esc_html_e( 'Request a Quote →', 'fireworks-phuket' ); ?></button></form><script>(function(){var s=document.querySelector('select[name=duration]'),w=document.getElementById('duration-other-wrap');if(!s||!w){return;}function t(){w.style.display='Other'===s.value?'':'none';}s.addEventListener('change',t);t();})();</script><?php endif; ?>
</div></div></section>
